######################################################################
# Automatically generated by qmake (3.0) ?? 9? 2 09:11:26 2015
######################################################################
QT       -= core gui sql

TEMPLATE = app
TARGET = cplusplus
INCLUDEPATH += .
CONFIG += c++11

#QMAKE_CXXFLAGS += -std=c++0x -pthread
LIBS += -pthread

QT -= qml quick widgets
# Input
HEADERS += \
    ../GDef.h \
    ../QJEventCenter.h \
    ../QJMutex.h

SOURCES += main.cpp \
    ../QJEventCenter.cpp


